// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvdctu4kn4VFOZcJBNSlPyTs9HNjmxpEu2xFZctz+5W5ElBZEvCCQkwAGhbE+l59j32ybbwwx+JlCJ7",
	"M9nZquTGFEgADXT31183kC845EnKGTAlcfcLTokgCSgQ5lefKDIlEobRFVEL3RKBDAVNFeUMd/Eto58z",
	"QDQCpuiMgkAzLpBaAIpcT+xheCRJGgPu4mTpV9qpHiHV43qYkUR/kL/9SCPsYQGfMyogwl0lMvCwDBeQ",
	"ECulUiB0/98/EP+Ptv/m7oV78O++tL3XnXXe/vJf/4Y9rJapHl8qQdkcr9frfLSNZdYXmL9BAiTPRKgf",
	"UgFSr5fNESnWiSiTirBQLywVPAWhKJjBQwFEwUdFk4bxxzQBqUiSoocFsI2dQw9EIttZb8aMi4Qou0fg",
	"m9H0DpHoPYuX+Q5tLdPDNHqO0qqL2aW9hDxeAJtrq3h97OGEsvxnx3u6fr66kLTR/q5zrejXlRVtyJ0L",
	"LYPNFXx1Tgninobw0b7YnvvGvkX67dbULEtw90MxMb5rGjyFUA/6NwEz3MU/BaUfBs40g9z6bvS3uo8i",
	"KjNGReL4/Qx3PxzY3/Zb320veu3hLI2eb54xkQrZEZ5ro+uqn3+w21LuF5/+E0KFPfzoE0j93AsrGCCr",
	"Oy2DLxUIWeuB0jgTJK6aAfawpGyexURUmkuQCFk6L+zEd0bgp4Lf0whEKwqTFuVB0U+vIN/o8zQz2oki",
	"qneQxFcVKLDL39zg86tbROKYh0Q3GEcEEi40ysQ0JIgyFHIBEnGBEhrH1P56Aa15y0MTfDTB+s9pu51M",
	"8Msa9iTksa7US/JIkywx8z5AhLQMz53476f5xKW/6Ta8iQEd/83dB+3tPydNcGzgo0FQyoyg84wIwhQ8",
	"V9bO9iaVsuq2p8m6Za9acAOGdaOt2MWAzSnbF17AfGBFRhOccqnmAuTn2AnsEKVsb8SUfLgLKlV9sisy",
	"p0x7KoqpVIjP6ngvaxbE4FF9TMkcPir+CRqUNNbNRicClKBwr+OiBgrdE+meeiYBMouVbFJ9/qr7BVMF",
	"iTwUFHVfNxgRgiyNanZq4BISLpZPc07bZ59/Ps/hEjtuzY4fqFqgjFFVMd23Z854O0eXZ87FG431xeXZ",
	"6u3Zany2uqRnq7f0bDWmZy//V872fyvnsxztEhTRVr2HKiTuE7OuPG5b/dbUGZMpxHK31Xypb+4WvmdS",
	"8QR9gqV/T+JMExUqpCVcZD43HJJFaEZjBWaEhrVZbrxzPfr1Jv94OjXz3dPPe1mzFUWmJGyQ5x/ZFAQD",
	"BRIVX2nWIEruLBERUKG0T2MGZhv26X4E6oGLT0/zcdcJhZzN6DwTzXaQctEEqFwoo8oCRxU32AoMcWet",
	"2qdw9/Xp6fGp0YT93SmWQZmCOQi9jnsq6ZTGVC33BIrKR2VY0IMIRmIT2tzjXdN+7ty7a+vacm8GZL0/",
	"5BlTuGkB5WBO38/gQqyAnSLjCjmTShDKVD08hZZwHRIvNDfT4FcEgkM6ubBhuDcXZA4HU3b3+bYVa4EL",
	"IfZZ843LD3ZoQ/PkArcsIlOWZgrNKMSRRRjjaU3mHHLGINSvPjrjqE1UmHT5Lbq9HqIXAmTKmQSfs3j5",
	"sjVhvxrS30WTrN0+Ds0+gHmGbhDYxkxqmyyabWNKpHzgIrKNv9jGBZeq/iUXyja48XLhbOOEDZJULVHG",
	"FI238liJRMYYZfPWhG0Qv5JJdYOApGlXHocC1C+a+k998dAq0oWWvA+7pyfHR/ozXAPQOweZr1r+3c/d",
	"IPjwe/DL3auu/fPLh9+7gf6lMfVV0Hp1UK4LBVs8xNIctzSmXQa/w4zbfa+RvQTPQ7rmWLs2pmUSo48L",
	"6mpIh7v8+9R+h/JB/NyukRkNzQRPjEpDokjM5+gFCUNIFUQeYlwhEmo+m6WcvWwKnaICa4csq4BBy0tL",
	"FDusc97hubUD9CLJpEJTQJPCATcTgL0lhXsQ0ox/mLy/uc9rKXhV9IpVFYZZ3Zu9EFaUK7ZJkRDAFLLl",
	"DJ0e7Cw+uWVfDUb94egt9vD17Whkn37tDS8Gfezh29E/Ru//fYQ93B9cDMaD/t7c6KbE8S2d2Bd70/GC",
	"+Vazy3Y7J79H429F0bd1tIcQ2C+K1LHzL1aWmCiQyopTG34gBBcNnPLXc/Tm5PTvSFtNTAlTCPSXKAd9",
	"9OJK8GkMCeqDIjS2cebdeHyFeldDqcPBhPVhRhlE2qfNp3p22Z2wFRprc9dRZIXGVMWAVravNRS0mrCV",
	"X/xbbf11v/Q4rVYrcKPLgLJ7EtPIJ2KeJdqsVmhom1Cl6aTdRvW+jCt/xjMWoRUacU3m7PNJ+6ThaxJr",
	"6F768EilkmiFerYBFQ0n7TcN/VIQCZVaS34EjIKe4apoQ0XbSfu4oXfGSKYWGiJCk7yv0G2t5aTdQU07",
	"Y7mg2RH3qJEHBDIGgFbotHFbMkbuCY3J1KgoB6vN1lMrbIVy9nkod9tUF+01HezhTMS4ixdKpbIbmPqa",
	"EiT8BKJFQc1aXMyDiIfBQiVxIGahHtTFnwq1iczgdTHeZQlhSKvLyA+PaUyY9fIi5CiO1IJKxMPQIFQI",
	"Tb5jPOKrQWFgv1p7uICzeiH+eogEzMBM5YrwVJbyWN/bkKaosGaC+kXfJjFTbtRfn/Xfbt6P0JV9i2aC",
	"zI2HVIOQVtnrN+0O+u//ev0SWTR0RR0dJ0CHKB4tLdVEakEUCkkmIbLyG7E95PDop0CvJygiRhCmWZBQ",
	"NsEt1JtKPXdRW7YLDgnToX0KiCgl6DTTNq44IkhSNo8bhdCpvLSMABnft6o1A1rqV+zcPyVnfr47TYX5",
	"HVHLmKoLWSGPNrRBmeq8riZ8p2/eVNO9drspX1IaAxsC0YIL5aGFtli/sFiZJQkRyyaJmznGpnU5/S5z",
	"RdqtdiE+D7OF74WJnwqu43lrTtUim7Yo34242Du0Z4G3h3fZBN3D+9VA9/CuW4h7eMdKHn74VDmmatZy",
	"oHt7+NHXOvPvicmrzBnIcPRb72LY712/vb0cjMbYw6P341/f3440R+pdXA96/f8c/MfwZnyDPXw1uL4c",
	"3twM34/6g9HQ0aje7fjdYDQenvfGpmU4Gg+uR70L+/K33vCid3YxwHfbhNFZkTXnJkJowLC/A5mHLKL3",
	"NMpIXPNcw7coQwQlWayov0lG8JOw32/EfsM9qazN/ANRvxmibhmLU9JOM2lA3it74I44i5duaQ/cHPZw",
	"AUiSBHyTSG2L6SJ5a8IGmsQDU2KJ7NBTkIizjS4zQuNMQAuNQDMkSFK19BDTPybM7pNvhmihMU/9GO4h",
	"RnY1CD5nJJZmx2dUSOXm0iF9SsJPD0REE6ZZAlGueme38KADj6r32Or90HY72j4A8fA7IHHTQbltz8OX",
	"XY3irCiy1Suejeft54RxRkOdsBO1yDO3yiBlgWVhJTnkmH1XwK3KXI1Spl1Hwozlz3f1qZ8QKotaesNZ",
	"fjHqYcfCxbJ3QvlX9yNLmw/jbyDkLDLa06IuADkhiuqJ3ithI1Yh9/FrTT52TFqtPu/KNG+2J5lmNI7y",
	"vHNjizqtdqv95MK+Cx+Fnt2VoHICtyFPvhXgdFG9BGCb8isAxgeK20XlnYBCiU+6EeB6rc3tIspm3JVa",
	"FQnN4YG749Q/v9SpkFvBZtLjGELIkypxCPbPXz910lPUbEODUUIYMYdORXUTUYYqRzdhnEkFQqJ7Sibs",
	"POZZNCKK3sPV29aEjXUw6l0N0YzHMX+QqDcwlJhFROQ1Z86kOQEJl4iEgkuJKtJIC3sxDYHZ61ZuU3op",
	"CReAjoz5bO7Jw8NDi5jXJgV0fWVwMTwfjG4G/lGr3dI5YYVR4w3BUVEryU35Kt+T3tWwYmm5Aa89zFNg",
	"JKW4i49b7daJs0oDUgFJaXDfIXG6IJ2gvFXS/YLnoJrAxRyLAyK1c3dpC0qpPZg3uWiWmrMmI4E9jBpG",
	"uIsvqFT9ygWW6jW9D7vOm1mWTEG443d3Aqc4EqAywZDhVS7+p2Re3Mj7nIFJM5xmEvJoz/8l/cO4aXEJ",
	"L4IZyWKFu6ftzVTo+KiaCnXaGoD2HX2tveZLBZRFtMKUDLjpH4ZqFJfW9sheubdQFXwbjsy1KMspjRqP",
	"2u3cdXV20/2CSWrqf1q6QLMd3VaOd0ix1VzJMMiwha5ZGIKUsyyOl/kNCohKC9HGeLJXHpdLvHqaXLYC",
	"2CDQGYlyOmjn7ny/uXtl2kUNOXFBwshx/P3kqBXntASn31MLRb1O2noduA89nNcBLCagKigoMjdxr2y7",
	"M2lL02Wgc3MKjwhi8NBYet/EH/t5v7wrtxeAimOdMKbAVH6oAxEa9muXTVtoODN5hotUkTdhObkBnQLG",
	"MZoD09IAIgwN+6bKfG2NQ6da0sUjHY78ztERKvjcsI98lAcSAmkrgvugc3QU/JQjok+jrZPBZOlH0x2A",
	"Yq4ll6r9tndgG2HJOOIZj5bfHJGs2W3esV7XkLDzJ8274zTDXQ5BsgKLPyDwrwKBJ+0330+Cc85mMQ0V",
	"8ksCZ+iSAQeSuJtPZOMM5i8J1A5rK+jZhNRrbxe1zDOLPQwzE8yWHxYbib5L0B37rqH6W1DvyjT9T2JA",
	"74q0yNuRWVKJ8pR9c+NcBeB8AeGnyq65Efdu2eY9cLNlMaimK7imXVPh/Njl69HQ9tkdDZu2o/wk2Ppf",
	"NQ3882TPhRy7kCaI/AFTuQQn30+CAptYfn78l8QgZ+ZfwSDvqynsbi9B0yUa9psw5k90lPb3pSdlgvaD",
	"oPzw/P8fnv8W1Feph7uw1pzNnY/21dCKel1g/NMNv6OWH+pIjgqAkGVmlbMEb+dFp5jOIFyGMdgqpsn8",
	"GocqV7a+W/9PAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
