// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvpctu4ln4VFO79kXRIkfKSO9GfadlSJ5prKy5b7pmpyJ2CyCMJNyTAAKBt3VjPM+8xTzaFhYtESpEz",
	"3ZmeqvSfyCCWg7N8Z0N/wRFPM86AKYl7X3BGBElBgTB/DYgiMyJhFF8RtdQjMchI0ExRznAP3zL6OQdE",
	"Y2CKzikINOcCqSWg2K3EHoZHkmYJ4B5OV35tnOodMr2vhxlJ9YTi60caYw8L+JxTATHuKZGDh2W0hJRY",
	"KpUCodf/9oH4/wz9N3cv3A//7kvove6ui/GX//pX7GG1yvT+UgnKFni9Xhe7bVyzecHiCxIgeS4i/SMT",
	"IPV92QKR8p6IMqkIi/TFMsEzEIqC2TwSQBR8VDRt2X9CU5CKpBl6WALb4Bx6IBLZxZoZcy5SoiyPwDe7",
	"aQ6R+D1LVgWHtq7pYRp/i9Dql9klvZQ8XgBbaK14fezhlLLiz673fPl89SJZq/5dF1LRn2s32qC7IFoG",
	"mzf46pkyg0if+VcBc9zDfwkqUwmc9gSFgtzouXqNIio3cidJ8n6Oex8OXG/Xre+26Vp7OM/ib9eghEiF",
	"7A7fqkbruil+sGy5K2fx2T8gUtjDjz6BzC8MpWamUq+qpPClZuVrvVGW5IIkdUlhD0vKFnlCRG24suOI",
	"ZYtSlL4EcU8j8DPB72kMohNHaYfyoFynb1Aw+jzLjXTimGoOkuSqZq32+psMPr+6RSRJeET0gLEVINFS",
	"A0FCI4IoQxEXIBEXKKVJQu1fL6Cz6Hhoio+mWP9zGobpFL9swENKHptCvSSPNM1Tc+4DxEjT8K0H/+20",
	"OLgyCT2GN82067+5+6AN8qe0DTGNhbcQSpkhdJETQZiCb6W1u82kitbT8Lm0bumrJtzgVVNpa3oxZAvK",
	"9nkAMBMsyWiKMy7VQoD8nDiCWZ7q06pxfNegrDrugkrVPOyKLCjTlooSKhXi8yYky4YGMXhUHzOygI+K",
	"f4IWIU30sJGJACUo3GvXpYFCr0R6pT5JgMwTJdtEX3zqfcFUQSoPBUW8LjcjQpAVXlcDTQlcQsrF6nnG",
	"adfss89vM7jU7tvQ4weqlihnVNVU9+2ZU97u0eWZM/FWZX1xefb09uxpcvZ0Sc+e3tKzpwk9e/m/Mrb/",
	"Wzq/ydAuQRGt1Xu8eeqmmHsVXt3KtyHOhMwgkbu15kuTuVv4nkvFU/QJVv49SXIdS1AhzdGKLBYmzGMx",
	"mtNEgdmh5W42fN15H/15Mzp5fvTku18/7Q1sLSkyI1ELPX/PZyAYKJConKWjBlGFtxIRAbWo83mRgWHD",
	"PtmPQT1w8el5Nu4WoYizOV3kol0PMi7aAJULZURZ4qjiBluBIe60VdsU7r0+PT0+NZKwf3fLa1CmYAFC",
	"3+OeSjqjCVWrPY6iNqlyC3oTwUhiXJv7edfGz528u7amLfcmKdb6I54zhdsuUG3m5P0NsRArYadMiiLO",
	"pBKEMtV0T1GWH+ovdGymwa90BIcscm7DxN5ckAUcHLK76dtarAkuidinzTcuP9ghDR0nl7hlEZmyLFdo",
	"TiGJLcIYS2tT54gzBpH+9NEpR+OgUqWruej2eoReCJAZZxJ8zpLVy86U/WKC/h6a5mF4HBk+gPkNvSCw",
	"g7nUOlkO28GMSPnARWwHf7aDSy5VcyYXyg64/Qri7OCUDdNMrVDOFE22Uk2JRM4YZYvOlG0EflUk1QsC",
	"kmU9eRwJUD/r0H/mi4dOsYfsyPuod3pyfKSn4QaA3jnIfNXx737qBcGH34Kf71717D8/f/itF+i/NKa+",
	"CjqvDkpHoYwWD9E0F1sa1a6c32HK7eZrZK/A85ClBdauPVwkRh+XlKlnmvz7zM5DxSZ+odfI7IbmgqdG",
	"pBFRJOEL9IJEEWQKYg8xrhCJdDybZ5y9bHOdogZrh1yrhEGztoZihy0uFmi4sGnjR0vStnXd2K9If63X",
	"Sl6kuVRoBmhaGuBmAlCMtob/9yCk2f8wen910xspeJ30mlaVilnnzV4IK8sV20GREMAUsuUMnR7srA+5",
	"a18Nx4PR+C328PXteGx//dIfXQwH2MO347+P3//7GHt4MLwYToaDvbnRTYXjWzKxH/am42XkW88uw7AI",
	"fo8mv1eIvi2jPQGBnVGmjt1/sbQkRIFUlpzG9kMhuGiJKX85R29OTv+GtNYklDCFQM9EBeijF1eCzxJI",
	"0QAUoYn1M+8mkyvUvxpJ7Q6mbABzyiBGmZuqT5e9KXtCE63u2os8oQlVCaAnu9YqCnqasie//O9p61/3",
	"l96n0+kEbncZUHZPEhr7RCzyVKvVExrZIVQbOglD1FzLuPLnPGcxekJjrlDx+yQ8aZlNEg3dKx8eqVQS",
	"PaG+HUDlwEn4pmVdBiKlUkvJj4FR0CdclWOoHDsJj1tW54zkaqkhIjLJ+xO6bYychF3UxhkbCxqOuJ8a",
	"eUAgowDoCZ22siVn5J7QhMyMiAqw2hw9tcTWQs4Bj+RuneqhvaqDPZyLBPfwUqlM9gJTX1OCRJ9AdCio",
	"eYeLRRDzKFiqNAnEPNKbOv9TC21is3mTjHd5ShjS4jL0w2OWEGatvHQ5iiO1pBLxKDIIFUGb7RiL+KpT",
	"GNpZaw+XcNaslV+PkIA5mKNcnZzKih5rexvUlBXWXFC/XNtGZsaN+Jun/tvN+zG6sl/RXJCFsZC6E9Ii",
	"e/0m7KL//q/XL5FFQ1fU0X4CtIvi8cqGmkgtiUIRySXEln5DtoccHv0l0PcJSo8RRFkepJRNcQf1Z1Kf",
	"XdaW7YUjwrRrnwEiSgk6y7WOK44I0mXbpJUIncpLGxEgY/tWtGZDG/qVnPuH5MwvuNPCOLnDaxlVtR9R",
	"xOMNaVCmuq/rCd/pmzf1dC8M2/IlpTGwxREtuVAeWmqN9UuNlXmaErFqo7g9xtjULiffVSFIy2rn4gs3",
	"W9pelOp6t/bnnQVVy3ymK947ERd7h64s8fbwJZuge/i6BugevnQLcQ9fWMvDDz+qwFR8V1Oo/eat2yFa",
	"Zv49MXmV6YGMxr/2L0aD/vXb28vheII9PH4/+eX97VjHSP2L62F/8J/D/xjdTG6wh6+G15ejm5vR+/Fg",
	"OB65MKp/O3k3HE9G5/2JGRmNJ8Prcf/Cfvy1P7ron10M8d12wOi0yKpzW0BowHCwA5lHLKb3NM5J0rBc",
	"E29RhghK80RRfzMYwc/Cfr8V+03sSWXj5B+I+rsh6payOCHtVJMW5L2yPXGkKw7uag/cNHu4ACRJCr7e",
	"q0Gm8+SdKRvqIB6YEitkt56BRJxtLJkTmuQCOmgMOkICXVPwENN/TJnlk2+26KAJz/wE7iFB9jYIPuck",
	"kYbjcyqkcmdplz4j0acHIuIp01ECUa56Z1l4UMOjbj22ej+yy462GyAefgckaetl2/HCfdnbKM7KIluz",
	"4tnaEj8njDMakcT2xF3mVtukKrAsLSWHdMJ3Odw6zXUvZca1J8xZ8fuuefQzXGVZS9/KxzcudFhbuLz2",
	"Tij/Kj/yrL0ZfwMRZ7GRniZ1CcgRUVZPNK+E9Vgl3cevw3DnofXq865M82b7kFlOk7jIOzdY1O2EnfDZ",
	"hX3nPko5u1c71QGOIc9+FeBkUX8EYIeKJwDGBgoia28CSiE+60WAW7U2D4Aom3NXalUkMs0D9wxpcH6p",
	"UyF3g82kx0UIEU/rgUOw//xm10kf0dANDUYpYcQ0nYrNpG6e11o3UZJLBUKie0qm7DzheTwmit7D1dvO",
	"lE20M+pfjdCc61amRP2hCYlZTERRc+ZMmg5ItEIkElxKVKNGWthLaARMQo0p/YxES0BHnbDBk4eHhw4x",
	"n00K6NbK4GJ0PhzfDP2jTtjROWEtosYbhKOyVlKo8lXBk/7VqKZphQKvPcwzYCSjuIePO2HnxGmlAamA",
	"ZDS475IkW5Ju+QzEfFqAagMX0xYHRBp9d2kLSpltzJtcNM9Mr8lQYJtRoxj3sO7oD0j1gKX+ku7Drn4z",
	"y9MZCNd+dx04xZEAlQuGTFzl/L9u0xeP5j7nYNIMJ5mUPNr+v6T/1HOqd3IxzEmeKNw7DTdToeOjeirU",
	"DcOwngs1wWfttT8qoCymtUjJgJv+w4Qa5buyPbTX3i3UCd+GI/MsysaURoxHYViYLjAjUZKZ+p+mLtDR",
	"jh6r9juk2KoFaJ8GbqFrHkUg5TxPklXxggLiSkO0Mp7spcflEq+eR5etALYQdEbiIhy0Z3e/39n9Ku2i",
	"JjhxTsLQcfz96GgU5zQFp99TCmW9Ttp6HbiJHi7qABYTUB0UFFkYv1eN3Zm0pe0x0LnpwiOCGDy0lt43",
	"8cdOH1Rv5fYCUNnWiRIKTBVNHYjRaNB4D9pBo7nJM5ynir0pK4Ib0ClgkqAFME0NIMLQaGCqzNdWOXSq",
	"JZ0/0u7I7x4doTKeGw2QjwpHQiDrxHAfdI+Ogr8UiOjTeKszqN9xznYAink5XIn2932m2gpLxhDPeLz6",
	"3RHJqt3mM+h1Awm7f9C5O7oZ7nEIkjVY/AGBfxYIPAnffD8KzjmbJzRSyK8COBMuGXAgqXv5RDZ6MH9K",
	"oHZYW0PPNqRee7tCyyKz2BNh5oLZ8sNyI9F3CbqLvhuo/hbUuypN/4MioHdlWuTtyCypREXKvsk4uxSd",
	"LyH6VOOa23EvyzbfgRuWJaDanuCacR0KF22Xr3tDu2a3N2xjRzUl2PofX1riz5M9D3LsRdog8gdMFRSc",
	"fD8KSmxiRf/4T4lBTs2/gkHeV1PY3VaCZis0GrRhzB9oKOH3DU+qBO1HgPLD8v9/WP5bUF8NPdyDtfZs",
	"7ny8r4ZW1usCY59u+x21/Eh7clQChKwyqyJK8HY+dEroHKJVlICtYprMr3Wr6mbru/X/DAA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
